#ifndef __TRAYTODAY_ERROR_H__
#define __TRAYTODAY_ERROR_H__
typedef enum {
  ERRCODE_OK = 0,
  ERRCODE_FILE_OPEN_FAILED,
  ERRCODE_FILE_READ_FAILED,
  ERRCODE_FILE_WRITE_FAILED,
  ERRCODE_INVALID_HEADER,
  ERRCODE_INVALID_VERSION,
  ERRCODE_INVALID_SETTINGS,
  ERRCODE_INVALID_CHECKSUM,
  ERRCODE_INVALID_FOOTER,
  ERRCODE_NULL_POINTER
} TrayTodayError;
#endif // __TRAYTODAY_ERROR_H__